# Generated by Django 2.1.7 on 2019-02-22 08:26

from django.db import migrations, models
import django.db.models.deletion
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('place_id', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=64)),
                ('province', models.CharField(choices=[('ON', 'Ontario'), ('QC', 'Quebec'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('MB', 'Manitoba'), ('BC', 'British Columbia'), ('PE', 'Prince Edward Island'), ('SK', 'Saskatchewan'), ('AB', 'Alberta'), ('NL', 'Newfoundland and Labrador')], default='ON', max_length=2)),
                ('postcode', models.CharField(max_length=6)),
                ('create_at', models.DateTimeField(default=utils.utils.get_timestamp)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=utils.utils.house_directory_path)),
                ('upload_at', models.DateTimeField(default=utils.utils.get_timestamp)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
            ],
        ),
    ]
