# Generated by Django 2.1.7 on 2019-02-28 16:11

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='date_begin',
            field=models.DateField(default=utils.utils.get_date_timestamp),
        ),
        migrations.AddField(
            model_name='house',
            name='date_end',
            field=models.DateField(default=utils.utils.get_date_timestamp),
        ),
        migrations.AlterField(
            model_name='house',
            name='create_at',
            field=models.DateTimeField(default=utils.utils.get_date_timestamp),
        ),
    ]
