# Generated by Django 2.1.7 on 2019-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
