# Generated by Django 2.1.7 on 2019-02-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20190228_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='number_of_beds',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
