# Generated by Django 2.1.7 on 2019-03-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_number_of_beds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-create_at']},
        ),
    ]
