# Generated by Django 2.1.7 on 2019-03-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20190301_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.CharField(default='no description', max_length=200),
        ),
    ]
