# Generated by Django 2.1.7 on 2019-03-18 14:13

from django.db import migrations, models
import django.db.models.deletion
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('house', '0005_house_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateTimeField(default=utils.utils.get_date_timestamp)),
                ('date_end', models.DateTimeField(default=utils.utils.get_date_timestamp)),
                ('create_at', models.DateTimeField(default=utils.utils.get_date_timestamp)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
