# Generated by Django 2.1.7 on 2019-03-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='house',
        ),
    ]
