# Generated by Django 2.1.7 on 2019-03-18 15:52

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20190318_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='create_at',
            field=models.DateField(default=utils.utils.get_date_timestamp),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_begin',
            field=models.DateField(default=utils.utils.get_date_timestamp),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_end',
            field=models.DateField(default=utils.utils.get_date_timestamp),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_at',
            field=models.DateField(default=utils.utils.get_date_timestamp),
        ),
    ]
