# Generated by Django 2.1.7 on 2019-03-18 19:53

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20190318_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='create_at',
            field=models.DateTimeField(default=utils.utils.get_date_timestamp),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_at',
            field=models.DateTimeField(default=utils.utils.get_date_timestamp),
        ),
    ]
