# Generated by Django 2.1.7 on 2019-03-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20190318_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='upload_at',
            new_name='create_at',
        ),
    ]
