# Generated by Django 2.1.7 on 2019-03-18 20:47

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20190318_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='create_at',
            field=models.DateTimeField(default=utils.utils.get_timestamp),
        ),
        migrations.AlterField(
            model_name='house',
            name='create_at',
            field=models.DateTimeField(default=utils.utils.get_timestamp),
        ),
        migrations.AlterField(
            model_name='photo',
            name='create_at',
            field=models.DateTimeField(default=utils.utils.get_timestamp),
        ),
    ]
